<?php
declare(strict_types=1);

namespace Nette\Bridges\HttpTracy;

use Tracy\Dumper;

?>
<style class="tracy-debug">
	#tracy-debug .nette-SessionPanel-parameters pre {
		background: #FDF5CE;
		padding: .4em .7em;
		border: 1px dotted silver;
		overflow: auto;
	}
</style>

<h1>Session #<?= htmlspecialchars(session_id(), ENT_IGNORE, 'UTF-8') ?> (Lifetime: <?= htmlspecialchars(ini_get('session.cookie_lifetime'), ENT_NOQUOTES, 'UTF-8'); ?>)</h1>

<div class="tracy-inner nette-SessionPanel">
	<?php if (empty($_SESSION)):?>
	<p><i>empty</i></p>
	<?php else: ?>
	<table>
	<?php
	foreach ($_SESSION as $k => $v) {
		if ($k === '__NF') {
			$k = 'Nette Session';
			$v = $v['DATA'] ?? null;
		} elseif ($k === '_tracy') {
			continue;
		}
		echo '<tr><th>', htmlspecialchars((string) $k, ENT_IGNORE, 'UTF-8'), '</th><td>', Dumper::toHtml($v, [Dumper::LIVE => true]), "</td></tr>\n";
	}?>
	</table>
	<?php endif ?>
</div>
